# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=63)),
                ('password', models.CharField(max_length=31)),
                ('fName', models.CharField(max_length=63)),
                ('lName', models.CharField(max_length=63)),
                ('gender', models.CharField(max_length=7)),
                ('birthdayY', models.IntegerField()),
                ('birthdayM', models.IntegerField()),
                ('birthdayD', models.IntegerField()),
                ('hobbies', models.CharField(max_length=255)),
            ],
        ),
    ]
