# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2047)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.APPUser')),
            ],
        ),
    ]
