# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='main_app.APPUser'),
        ),
    ]
